-- MySQL Script generated by MySQL Workbench
-- Wed Mar 14 21:57:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(150) NULL,
  `user_nickname` VARCHAR(45) NOT NULL,
  `user_avatar` VARCHAR(1024) NULL,
  `user_cpf` VARCHAR(11) NULL,
  `user_birth_date` DATETIME NULL,
  `user_sex` VARCHAR(1) NULL,
  `user_cep` VARCHAR(8) NULL,
  `user_email` VARCHAR(150) NULL,
  `user_password` VARCHAR(45) NULL,
  `user_access` INT NULL,
  `user_preferences` VARCHAR(4096) NULL,
  `user_address_details` VARCHAR(45) NULL,
  `user_favorite_post` VARCHAR(150) NULL,
  `user_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `post_id` INT NOT NULL,
  `post_title` VARCHAR(150) NOT NULL,
  `post_user_id` INT NOT NULL,
  `post_date_time` DATETIME NOT NULL,
  `post_photos` VARCHAR(4096) NOT NULL,
  `post_operating_hours_start` VARCHAR(45) NOT NULL,
  `post_operating_hours_end` VARCHAR(45) NOT NULL,
  `post_days_of_operating` VARCHAR(45) NOT NULL,
  `post_price` VARCHAR(45) NOT NULL,
  `post_event_date_start` VARCHAR(45) NOT NULL,
  `post_event_date_end` VARCHAR(45) NOT NULL,
  `post_price` VARCHAR(50) NOT NULL,
  `post_tags` VARCHAR(4096) NOT NULL,
  `post_description` VARCHAR(10000) NOT NULL,
  `post_category` INT NOT NULL,
  `post_references` VARCHAR(4096) NULL,
  `post_rating` VARCHAR(45) NOT NULL,
  `post_status` VARCHAR(45) NOT NULL,
  `post_status_reason` VARCHAR(45) NULL,
  `post_cep` VARCHAR(8) NOT NULL,
  `post_address_details` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `comment_id` INT NOT NULL,
  `comment_post_id` VARCHAR(45) NOT NULL,
  `comment_user_id` VARCHAR(45) NOT NULL,
  `comment_comment_id` VARCHAR(45) NULL,
  `comment_description` VARCHAR(2048) NOT NULL,
  `comment_status` INT NULL,
  `comment_status_reason` VARCHAR(45) NULL,
  PRIMARY KEY (`comment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `category_id` INT NOT NULL,
  `category_level` INT NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `category_description` VARCHAR(200) NOT NULL,
  `category_status` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
